version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: api-gateway-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
